#! /usr/bin/env bash
function set-title ()
{
    echo -ne "\e]2;$@\007"
}

function magic ()
{
  set-title "target$1"
}

magic ' '

while read -s -n1 v
do
  case $v in
    r ) magic '\011' ;;
    g ) magic '\037' ;;
    b ) magic '\036' ;;
    q ) exit 0 ;;
    * ) magic ' ' ;;
  esac

done
